trainer:
  epochs: 1000
  batch_size: 32
  lr: 1.0e-4
  output_path: tts/checkpoints

data:
  sample_rate: 22050
  n_mel_channels: 80
  speakers: [ken, kelly]
  manifest_csv: tts/manifests/primary.csv
  root: "/Users/nicolette/Downloads/my-next-lesson/tts_training 2"

model:
  name: vits_multispeaker
  phoneme_language: en


